### ISSUE TITLE
Create tests for Android and IOS OS

### ISSUE THREAD

**Issue by toor1245** [toor1245/MatrixDotNet#83]
need create tests for android and ios os for testing how will execute tests on mobile devices

**Comment by Dilorfin** [comment]
For ARM tests run can be created, but how is it proposed to run automated tests on ios or android?

**Comment by Dilorfin** [comment]
After some investigation here I have two links:

https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/automate-android-nunit-test

https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/touch.unit

ios specific tests should be run using simulator and the result should than be parsed. [[link](https://forums.xamarin.com/discussion/90901/how-i-do-i-automate-xamarin-ios-unit-test-project)]

Both of this articles are using NUnitLite, Xamarin specific version of NUnit. Here we have to create Xamarin projects for each platform and add some 'test runners' to them.

ios specific project should be created using VS for MacOS and other interesting details about this platform...

So I think that creating tests for ios is overcomplicated for such project as Matrix and propose just keep not forgetting to write usual C# managed platform-independent code to keep compatibility with all .Net platforms.

**Comment by Dilorfin** [comment]
instead will be created #110 #111
